name: SonarQube Analysis Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  sonar:
    runs-on: self-hosted # Ensure your runner has the 'self-hosted' label

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # Step 3: Install Maven with lock handling
      - name: Install Maven
        run: |
          # Wait and retry if lock file exists
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for lock to be released..."
            sleep 5
          done

          # If lock still exists, remove it
          sudo rm -f /var/lib/dpkg/lock-frontend
          sudo rm -f /var/lib/dpkg/lock
          sudo rm -f /var/cache/apt/archives/lock
          
          # Fix any broken dpkg process
          sudo dpkg --configure -a
          
          # Install Maven
          sudo apt-get update
          sudo apt-get install -y maven

      # Step 4: SonarQube Analysis (using credentials)
      - name: SonarQube Analysis
        env:
          SONAR_HOST_URL: http://172.27.59.119:9000
          SONAR_USERNAME: ${{ secrets.SONAR_USERNAME }}
          SONAR_PASSWORD: ${{ secrets.SONAR_PASSWORD }}
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_USERNAME }} \
            -Dsonar.password=${{ env.SONAR_PASSWORD }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  notify:
    runs-on: ubuntu-latest
    needs: sonar
    if: always()  # Run this job regardless of the result of previous jobs

    steps:
      # Step 1: Send notification to Slack using Incoming Webhook
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "SELF HOSTED SonarQube analysis of calculator completed with status: ${{ needs.sonar.result }}."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
